name: waseet
description: app for buy and sell real-estates
version: 1.0.16+3
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  app_links: ^6.1.3
  auto_size_text: ^3.0.0
  bloc: ^9.1.0
  cloud_firestore: ^6.1.0
  dio: ^5.3.4
  dotted_border: ^2.1.0
  equatable: ^2.0.5
  file_picker: ^10.3.6
  firebase_core: ^4.2.1
  firebase_messaging: ^16.0.4
  firebase_storage: ^13.0.4
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_easyloading: ^3.0.5
  flutter_image_slideshow: ^0.1.6
  flutter_local_notifications: ^19.5.0
  flutter_localizations:
    sdk: flutter
  flutter_rating_bar: ^4.0.1
  flutter_screenutil: ^5.9.0
  flutter_svg: ^2.0.9
  formz: ^0.6.1
  geolocator: ^10.1.0
  go_router: ^13.0.1
  google_fonts: ^6.1.0
  google_maps_flutter: ^2.5.0
  image_picker: ^1.0.4
  internet_connection_checker: ^1.0.0+1
  internet_connection_checker_plus: ^2.2.0
  intl: ^0.18.1
  moyasar: ^2.0.6
  multi_dropdown: ^2.1.4
  pretty_dio_logger: ^1.3.1
  share_plus: ^12.0.1
  shared_preferences: ^2.2.2
  shimmer: ^3.0.0
  url_launcher: ^6.2.6
  video_player: ^2.10.1
  webview_flutter: ^4.7.0

dependency_overrides:
  http: ^0.13.4
  intl: ^0.18.1

dev_dependencies:
  bloc_test: ^10.0.0
  build_runner: ^2.4.7
  flutter_gen_runner: ^5.12.0
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.1
  simple_deploy:
    git:
      url: https://github.com/rashedswen/simple_deploy
      ref: main
  very_good_analysis: ^5.1.0
  change_app_package_name: ^1.4.0


flutter_gen:
  output: lib/res/assets/ # Optional (default: lib/gen/)
  line_length: 100 # Optional (default: 80)
  integrations:
    flutter_svg: true

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/
    - assets/images/
    - assets/icons/
